[project]
name = "example-deepagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepagents>=0.1.4",
    "langgraph-cli[inmem]>=0.4.4",
    "tavily-python>=0.7.12",
]
